{% set name = "geventhttpclient" %}
{% set version = "1.5.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: d80ec9ff42b7219f33558185499d0b4365597fc55ff886207b45f5632e099780

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - brotli-python
    - certifi
    - gevent >=0.13
    - six

test:
  requires:
    - pip
  imports:
    - geventhttpclient
  commands:
    - python -m pip check

about:
  home: https://github.com/gwik/geventhttpclient
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: A high performance, concurrent http client library for python with gevent
  description: |
    gevent.httplib support was removed in gevent 1.0, geventhttpclient now
    provides that missing functionality.

    geventhttpclient uses a fast http parser, written in C, originating from
    nginx, extracted and modified by Joyent.

    geventhttpclient has been specifically designed for high concurrency,
    streaming and support HTTP 1.1 persistent connections. More generally it is
    designed for efficiently pulling from REST APIs and streaming APIs
    like Twitter's.

    Safe SSL support is provided by default. geventhttpclient depends on
    the certifi CA Bundle. This is the same CA Bundle which ships with the
    Requests codebase, and is derived from Mozilla Firefox's canonical set.
    As of 1.5, only Python 3.6+ is fully supported (with prebuilt wheels), 
    but Python 2.7 and 3.5 *should* work too.

    Use of SSL/TLS with python 2.7.9 is not recommended and may be broken.

extra:
  recipe-maintainers:
    - bollwyvl
