{% set version = "2.1.1" %}

package:
  name: geventhttpclient
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geventhttpclient/geventhttpclient-{{ version }}.tar.gz
  sha256: e0a7d93773024d0168e4da1fe36131f555d3d7b8f87b7a7b5e64012a5d0d3914

build:
  number: 0
  skip: true  # [py < 39 or (python_impl == "pypy" and (aarch64 or ppc64le))]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - brotli-python
    - certifi
    - gevent >=0.13
    - python
    - urllib3

test:
  source_files:
    - pyproject.toml
    - src/geventhttpclient/tests
  requires:
    - dpkt
    - pip
    - pytest-cov
    - requests
  imports:
    - geventhttpclient
  commands:
    - pip check
    {% set skips = "brotli_response" %}
    {% set pytest = 'pytest -vv --color=yes --tb=long -m "not online" -k "not ' + skips + '"' %}
    {% set pytest = 'coverage run --branch -m ' + pytest %}  # [python_impl != "pypy"]
    - {{ pytest }} src/geventhttpclient/tests  # [not win]
    - coverage report --show-missing --skip-covered --fail-under=82  # [not (win or python_impl == "pypy")]

about:
  home: https://github.com/geventhttpclient/geventhttpclient
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - llhttp/LICENSE-MIT
  summary: A high performance, concurrent http client library for python with gevent

extra:
  recipe-maintainers:
    - bollwyvl
