{% set pytest = "pytest -vv --color=yes --tb=long -m \"not online\" -k \"not brotli_response\"" %}
{% set version = "2.3.3" %}

package:
  name: geventhttpclient
  version: {{ version }}

source:
  # pypi doesn't consistently have `tests``
  - folder: dist
    url: https://pypi.org/packages/source/g/geventhttpclient/geventhttpclient-{{ version }}.tar.gz
    sha256: 3e74c1570d01dd09cabdfe2667fbf072520ec9bb3a31a0fd1eae3d0f43847f9b
  - folder: src
    url: https://github.com/geventhttpclient/geventhttpclient/archive/refs/tags/{{ version }}.tar.gz
    sha256: c94fe21977cf3fdd0d76792ea12c40eb623bb03a0b8f04bbc85cca10f1d1101d

build:
  number: 0
  skip: true  # [py < 39 or (python_impl == "pypy" and (aarch64 or ppc64le))]
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - brotli-python
    - certifi
    - gevent
    - python
    - urllib3

test:
  source_files:
    - src/pyproject.toml
    - src/tests
  requires:
    - coverage
    - dpkt
    - pip
    - pytest
    - requests
  imports:
    - geventhttpclient
  commands:
    - pip check
    {% set pytest = 'pytest -vv --color=yes --tb=long -m "not online" -k "not brotli_response"' %}
    {% set pytest = 'coverage run --source=geventhttpclient --branch -m ' + pytest %}               # [python_impl != "pypy"]
    - cd src && {{ pytest }}                                                                        # [unix]
    - coverage report --show-missing --skip-covered --fail-under=72                                 # [unix and python_impl != "pypy"]

about:
  home: https://github.com/geventhttpclient/geventhttpclient
  license: MIT
  license_family: MIT
  license_file:
    - dist/LICENSE-MIT
    - dist/llhttp/LICENSE-MIT
  summary: A high performance, concurrent http client library for python with gevent

extra:
  recipe-maintainers:
    - bollwyvl
