{% set version = "2.3.4" %}

package:
  name: geventhttpclient
  version: {{ version }}

source:
  # pypi doesn't consistently have `tests``
  - folder: dist
    url: https://pypi.org/packages/source/g/geventhttpclient/geventhttpclient-{{ version }}.tar.gz
    sha256: 1749f75810435a001fc6d4d7526c92cf02b39b30ab6217a886102f941c874222
  - folder: src
    url: https://github.com/geventhttpclient/geventhttpclient/archive/refs/tags/{{ version }}.tar.gz
    sha256: 4256b59d4ec9a9f3a827125fcc1c2f3c47abbda19716a71ae9c3a4844746f1cc

build:
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - brotli-python
    - certifi
    - gevent
    - python
    - urllib3

test:
  source_files:
    - src/pyproject.toml
    - src/tests
  requires:
    - coverage
    - dpkt
    - pip
    - pytest
    - requests
  imports:
    - geventhttpclient
  commands:
    - pip check

about:
  home: https://github.com/geventhttpclient/geventhttpclient
  license: MIT
  license_family: MIT
  license_file:
    - dist/LICENSE-MIT
    - dist/llhttp/LICENSE-MIT
  summary: A high performance, concurrent http client library for python with gevent

extra:
  recipe-maintainers:
    - bollwyvl
