{% set version = "2.0.8" %}

package:
  name: geventhttpclient
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geventhttpclient/geventhttpclient-{{ version }}.tar.gz
  sha256: 5f782c419643f74be4d0918c0d2b63956ef6ddc7a2127f07cbb8033a75ab366f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [python_impl == "pypy" and (aarch64 or ppc64le)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - brotli-python
    - certifi
    - gevent >=0.13
    - six

test:
  source_files:
    - pytest.ini
    - src/geventhttpclient/tests
  requires:
    - dpkt
    - pip
    - pytest-cov
    - mock
    - requests
  imports:
    - geventhttpclient
  commands:
    - python -m pip check
    {% set pytest_args = '-k "not brotli_response"' %}  # [not win]
    {% set pytest_args = '-k "not (brotli_response or readline_multibyte_sep or file_post or close or server_error_with_file or simple_ssl or readline_multibyte_splitsep or verify_hostname or internal_server_error or implicit_sni_from_host_in_ssl
)"' %}  # [win]
    {% set pytest_args = pytest_args + " --cov=geventhttpclient --cov-branch --no-cov-on-fail --cov-fail-under=71" %}  # [win or python_impl != "pypy"]
    - pytest -vv src/geventhttpclient/tests {{ pytest_args }}

about:
  home: https://github.com/geventhttpclient/geventhttpclient
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - llhttp/LICENSE-MIT
  summary: A high performance, concurrent http client library for python with gevent
  description: |
    gevent.httplib support was removed in gevent 1.0, geventhttpclient now
    provides that missing functionality.

    geventhttpclient uses a fast http parser, written in C, originating from
    nginx, extracted and modified by Joyent.

    geventhttpclient has been specifically designed for high concurrency,
    streaming and support HTTP 1.1 persistent connections. More generally it is
    designed for efficiently pulling from REST APIs and streaming APIs
    like Twitter's.

    Safe SSL support is provided by default. geventhttpclient depends on
    the certifi CA Bundle. This is the same CA Bundle which ships with the
    Requests codebase, and is derived from Mozilla Firefox's canonical set.
    As of 1.5, only Python 3.6+ is fully supported (with prebuilt wheels),
    but Python 2.7 and 3.5 *should* work too.

    Use of SSL/TLS with python 2.7.9 is not recommended and may be broken.

extra:
  recipe-maintainers:
    - bollwyvl
