{% set name = "geventhttpclient" %}
{% set version = "1.4.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: f59e5153f22e4a0be27b48aece8e45e19c1da294f8c49442b1c9e4d152c5c4c3
  - url: https://raw.githubusercontent.com/gwik/{{ name }}/master/LICENSE-MIT
    sha256: 5a2f8f840ffb3e61c0f4aa3df14fff2c0bc28bdcf5d0d1e6582dab418aa79e3c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - gevent >=0.13
    - certifi
    - six

test:
  requires:
    - pip
  imports:
    - geventhttpclient
  commands:
    - python -m pip check

about:
  home: https://github.com/gwik/geventhttpclient
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: A high performance, concurrent http client library for python with gevent

  # The remaining entries in this section are optional, but recommended.
  description: |
    gevent.httplib support was removed in gevent 1.0, geventhttpclient now provides
    that missing functionality.

    geventhttpclient use a fast http parser, written in C, originating from nginx,
    extracted and modified by Joyent.

    geventhttpclient has been specifically designed for high concurrency, streaming
    and support HTTP 1.1 persistent connections. More generally it is designed for
    efficiently pulling from REST APIs and streaming APIs like Twitter's.

    Safe SSL support is provided by default. geventhttpclient depends on the certifi
    CA Bundle. This is the same CA Bundle which ships with the Requests codebase, and
    is derived from Mozilla Firefox's canonical set.

    Python 2.7 and 3.4+ are supported. Python 2.6 is no longer supported.

    Use of SSL/TLS with python 2.7.9 is not recommended and may be broken.

extra:
  recipe-maintainers:
    - bollwyvl
