# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.6.0"

package:
  name: geventhttpclient
  version: ${{ version }}

source:
  # pypi doesn't consistently have `tests``
  - url: https://pypi.org/packages/source/g/geventhttpclient/geventhttpclient-${{ version }}.tar.gz
    sha256: 95f57d382d04319233a72f85bd8dcf30a422385d3e45a9fdd9d5e4694433a28c
    target_directory: dist
  - url: https://github.com/geventhttpclient/geventhttpclient/archive/refs/tags/${{ version }}.tar.gz
    sha256: fc4b3c75cc56e6d511a12bc09c9450ab04b1a6185dad4e0f56e433f33a527ad7
    target_directory: src

build:
  skip:
    # `gevent` will not be migrated: see https://github.com/conda-forge/gevent-feedstock/pull/84
    - target_platform == "linux-ppc64le" and match(python, ">=3.15")
  number: 0
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check --check-build-dependencies

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - brotli-python
    - certifi
    - gevent
    - python

tests:
  - package_contents:
      strict: true
      files:
        - etc/conda/test-files/geventhttpclient/**
      site_packages:
        - geventhttpclient/**
        - geventhttpclient-${{ version }}.dist-info/**
  - python:
      imports: geventhttpclient
      pip_check: true
  - files:
      recipe:
        - run_test.py
      source:
        - src/pyproject.toml
        - src/tests/
    requirements:
      run:
        - coverage
        - dpkt
        - pip
        - pytest
        - requests
    script:
      - python run_test.py

about:
  license: MIT
  license_file:
    - dist/LICENSE-MIT
    - dist/llhttp/LICENSE-MIT
  summary: A high performance, concurrent http client library for python with gevent
  homepage: https://pypi.org/project/geventhttpclient
  repository: https://github.com/geventhttpclient/geventhttpclient

extra:
  recipe-maintainers:
    - bollwyvl
