# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.3.4

package:
  name: geventhttpclient
  version: ${{ version }}

source:
  # pypi doesn't consistently have `tests``
  - url: https://pypi.org/packages/source/g/geventhttpclient/geventhttpclient-${{ version }}.tar.gz
    sha256: 1749f75810435a001fc6d4d7526c92cf02b39b30ab6217a886102f941c874222
    target_directory: dist
  - url: https://github.com/geventhttpclient/geventhttpclient/archive/refs/tags/${{ version }}.tar.gz
    sha256: 4256b59d4ec9a9f3a827125fcc1c2f3c47abbda19716a71ae9c3a4844746f1cc
    target_directory: src

build:
  number: 0
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - setuptools
  run:
    - brotli-python
    - certifi
    - gevent
    - python
    - urllib3

tests:
  - python:
      imports: geventhttpclient
  - files:
      recipe:
        - run_test.py
      source:
        - src/pyproject.toml
        - src/tests/
    requirements:
      run:
        - coverage
        - dpkt
        - pip
        - pytest
        - requests
    script:
      - python run_test.py

about:
  license: MIT
  license_file:
    - dist/LICENSE-MIT
    - dist/llhttp/LICENSE-MIT
  summary: A high performance, concurrent http client library for python with gevent
  homepage: https://github.com/geventhttpclient/geventhttpclient

extra:
  recipe-maintainers:
    - bollwyvl
